version: "3.9"

services:
  minio1:
    image: minio/minio
    container_name: minio1
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # CONSOLE WEB
    volumes:
      - data1:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: superSenha123
    command: server http://minio{1...4}/data --console-address ":9001"
    restart: always

  minio2:
    image: minio/minio
    container_name: minio2
    volumes:
      - data2:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: superSenha123
    command: server http://minio{1...4}/data --console-address ":9001"
    restart: always

  minio3:
    image: minio/minio
    container_name: minio3
    volumes:
      - data3:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: superSenha123
    command: server http://minio{1...4}/data --console-address ":9001"
    restart: always

  minio4:
    image: minio/minio
    container_name: minio4
    volumes:
      - data4:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: superSenha123
    command: server http://minio{1...4}/data --console-address ":9001"
    restart: always

volumes:
  data1:
  data2:
  data3:
  data4:
